language: python
sudo: false
notifications:
  email: false
python:
- '2.7'
before_install:
- ! '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_c3e85137836d_key -iv $encrypted_c3e85137836d_iv -in .env.enc -out .env -d || true'
install:
- pip install -r requirements.txt
- pip install pylint
- pip install codecov
script:
- sh tests/pylint.sh
- py.test test --cov=glpi-sdk-python
after_success:
- codecov
