language: python
sudo: false
notifications:
  email: false
python:
- '2.7'
install:
- make dependencies
- pip install git+git://github.com/truly-systems/glpi-sdk-python.git#egg=glpi
script:
- make check-syntax
